name: ProtectGaldur
main: com.github.inclusiverec.protectgaldur.ProtectGaldur
version: 1.0.0-SNAPSHOT
commands:
  build:
    description: Used for creating protected areas.
    usage: "Type /build help for information on the building process."